### ISSUE TITLE
this.collideSpriteVsTilemapLayer is not a function

### ISSUE THREAD

**Issue by tgeorge91** [photonstorm/phaser-examples#104]
http://phaser.io/examples/v2/tilemaps/create-from-objects

This example is not loading... When you open the console you see:

Uncaught TypeError: this.collideSpriteVsTilemapLayer is not a function

**Comment by Pajamaman** [comment]
I think something weird happened with the 2.4.3 build that's currently used by the examples, because `Phaser.Physics.Arcade.TilemapCollision` is undefined. I created a new 2.4.3 build and used it and it worked. It also worked on 2.4.2.

I can't find a change in since Aug 5 (when the build was updated) that would account for that object gone missing so... dunno. It just needs to be redeployed.

**Comment by hlfcoding** [comment]
Help @photonstorm, this literally breaks all examples in the Tilemaps section.
